### ISSUE TITLE
Something Special

### ISSUE THREAD

**Issue by HansongYang** [largetimmo/AutoBooking#1]
Dear Haohao,

  There are somethings that you need to consider carefully, because it is important based on users' perspective. First of all, you need to add some preferences, such as number of people, floor number and most importantly, don't forget the Discovery Centre. You never know what users really like and want.
  This is an interesting repo, but you've got a lot of things to improve. Carry on and make the best of it.

HY

**Comment by HansongYang** [comment]
This is just a kindly reminder, not a real issue. Take it easy.

**Comment by largetimmo** [comment]
Ok
